use_frameworks!

platform :ios, '8.0'

target 'PodTestLibrary_Example' do
  pod 'PodTestLibrary', :path => '../'

  target 'PodTestLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
